/*
 * This source file was generated by the Gradle 'init' task
 */
package javagame;

import javax.swing.JFrame;

public class App {
  

    public static void main(String[] args) {
        JFrame window = new JFrame();
        window.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        window.setResizable(false);
        window.setTitle("Java Game Baby!");

        GamePanel gamePanel = new GamePanel();
        window.add(gamePanel);

        window.pack();

        gamePanel.startGameThread();

        window.setLocationRelativeTo(null);
        window.setVisible(true);
    }
}
